apiVersion: v1
kind: Service
metadata:
  name: test-sts-mix-scheduler
  labels:
    app: test-sts-mix-scheduler
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: test-sts-mix-scheduler
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-sts-mix-scheduler
spec:
  serviceName: "test-sts-mix-scheduler"
  replicas: 10
  selector:
    matchLabels:
      app: test-sts-mix-scheduler
  template:
    metadata:
      labels:
        app: test-sts-mix-scheduler
    spec:
      containers:
      - name: nginx
        image: nginx:1.23-alpine
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
              cpu: 10m
              memory: 10Mi
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Mi
